"==============================================================================
" settings
"==============================================================================
set number              " line numbers
set tabstop=4
set shiftwidth=4
set expandtab           " replace tabs with spaces
set autoindent          " indent according to language
set fileencodings=utf8
set colorcolumn=80      " make the 80th colmn visible
set cursorcolumn        " show a column at cursor position
set cursorline          " make the cursor line visible
set foldmethod=indent   " fold code with same indention level
set foldlevelstart=20   " fold very late when opening file
set background=dark     " dark background
set tw=79               " force hard wrap at 79 characters
set formatoptions+=t

"==============================================================================
" colors 
"==============================================================================
hi CursorLine   cterm=NONE ctermbg=blue ctermfg=white guibg=darkred guifg=white
hi CursorColumn cterm=NONE ctermbg=blue ctermfg=white guibg=darkred guifg=white
"colorscheme github      " use github color scheme
"highlight OverLength cterm=underline
"ctermbg=red ctermfg=white guibg=#592929
"match OverLength /\%81v.\+/

"==============================================================================
" key mappings 
"==============================================================================
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
nnoremap <Leader>c :set cursorline! cursorcolumn! <CR>
nnoremap <space> za
vnoremap <space> zf
nmap n nzz
nmap N Nzz
"nmap <space> zz
imap ,t <Esc>:tabnew<CR>

"==============================================================================
" etc
"==============================================================================
syntax on
syntax enable
" set syntax highlighting for glsl
au BufNewFile,BufRead *.frag,*.vert,*.fp,*.vp,*.glsl setf glsl 

"==============================================================================
" plugins 
"==============================================================================
execute pathogen#infect()
call pathogen#runtime_append_all_bundles()
filetype plugin indent on
" nifty: puge all trailing whitespaces :%s/\s\+$//
